#!/usr/bin/env python3
"""
Plot global v0 emulator predictions against ATLAS 5.02 TeV experimental data.
Creates separate plots for each viscous correction with model/data ratio panels.

FIX: Ensures theoretical predictions and experimental data share the same
     centrality bin centers (starting at 2.5%) and clips predictions to
     the last experimental centrality bin.
"""
import numpy as np
import pandas as pd
import pickle
import matplotlib.pyplot as plt
from pathlib import Path

# =============================================================================
# PLOTTING STYLE (Gardim style)
# =============================================================================

plt.rcParams["xtick.major.size"] = 6
plt.rcParams["ytick.major.size"] = 6
plt.rcParams["xtick.minor.size"] = 3
plt.rcParams["ytick.minor.size"] = 3
plt.rcParams["xtick.major.width"] = 1.2
plt.rcParams["ytick.major.width"] = 1.2
plt.rcParams["xtick.minor.width"] = 1
plt.rcParams["ytick.minor.width"] = 1
plt.rcParams["axes.linewidth"] = 1
plt.rcParams["lines.linewidth"] = 1
plt.rcParams["xtick.major.pad"] = 4
plt.rcParams["ytick.major.pad"] = 4
plt.rcParams["xtick.minor.pad"] = 4
plt.rcParams["ytick.minor.pad"] = 4
plt.rcParams["legend.handletextpad"] = 0.0
plt.rcParams["xtick.direction"] = 'in'
plt.rcParams["ytick.direction"] = 'in'
plt.rcParams["xtick.minor.visible"] = True
plt.rcParams["ytick.minor.visible"] = True
plt.rc('text', usetex=False)
plt.rc('font', family='serif')

# =============================================================================
# CONFIGURATION
# =============================================================================

# Experimental data file (ATLAS 5.02 TeV)
EXP_V0_FILE = 'experimental_data/differential_radial_flow/HEPData-ins2907010-v1-Figure_2a.csv'

# Prediction file (generated by predict_global_v0.py)
PREDICTIONS_FILE = "predictions_global_v0/all_predictions_global_v0.pkl"

# Output folder
OUTPUT_FOLDER = "predictions_global_v0_vs_exp"

# Viscous corrections
VISCOUS_CORRECTIONS = ["Grad", "CE", "PTM", "PTB"]
COLOR_NAMES = {"Grad": 'blue', "CE": 'red', "PTM": 'magenta', "PTB": 'green'}

# Correct centrality bin edges (matching ATLAS: 0-5, 5-10, 10-20, ..., 70-80%)
# and their centers:  2.5, 7.5, 15, 25, 35, 45, 55, 65, 75
CENTRALITY_EDGES = [0, 5, 10, 20, 30, 40, 50, 60, 70, 80]
CENTRALITY_CENTERS_CORRECT = np.array(
    [(CENTRALITY_EDGES[i] + CENTRALITY_EDGES[i+1]) / 2.0
     for i in range(len(CENTRALITY_EDGES) - 1)]
)  # [2.5, 7.5, 15, 25, 35, 45, 55, 65, 75]

CENTRALITY_LABELS = ["0-5%", "5-10%", "10-20%", "20-30%", "30-40%", "40-50%",
                     "50-60%", "60-70%", "70-80%"]

Path(OUTPUT_FOLDER).mkdir(parents=True, exist_ok=True)

# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================

def configure_axis(ax, fontsize):
    """Configure axis ticks"""
    ax.yaxis.set_ticks_position('both')
    ax.xaxis.set_ticks_position('both')
    ax.tick_params(labelsize=fontsize)


def save_fig(fig, filename):
    """Save figure"""
    filepath = Path(OUTPUT_FOLDER) / filename
    fig.savefig(filepath, dpi=300, bbox_inches='tight')
    print(f"  Saved: {filepath}")
    plt.close(fig)


# =============================================================================
# CENTRALITY BIN ALIGNMENT
# =============================================================================

def remap_predictions_to_correct_centrality(pred_data):
    """
    Remap prediction centrality centers to the correct ATLAS bin centers.

    The predictions file may have stored wrong centrality centers (e.g. starting
    at 0 instead of 2.5, or using uniform 10%-wide bins instead of the actual
    non-uniform ATLAS bins).  We assume there is a one-to-one correspondence
    between the N prediction bins and the N correct centrality bins and simply
    replace the stored centers with CENTRALITY_CENTERS_CORRECT.

    If the number of prediction bins does not match, we fall back to linear
    interpolation onto the correct grid.
    """
    stored_centers = np.asarray(pred_data['centrality_centers'])
    n_pred = len(stored_centers)
    n_correct = len(CENTRALITY_CENTERS_CORRECT)

    if n_pred == n_correct:
        print(f"    Remapping {n_pred} prediction bins:")
        print(f"      Stored centers : {stored_centers}")
        print(f"      Correct centers: {CENTRALITY_CENTERS_CORRECT}")
        # Direct replacement — bin i of predictions corresponds to bin i of ATLAS
        remapped = pred_data.copy()
        remapped['centrality_centers'] = CENTRALITY_CENTERS_CORRECT.copy()
        return remapped
    else:
        print(f"    WARNING: {n_pred} prediction bins vs {n_correct} correct bins.")
        print(f"    Falling back to interpolation onto correct centrality grid.")
        remapped = pred_data.copy()
        for key in ('prior', 'original_posterior', 'posterior'):
            arr = pred_data.get(key)
            if arr is not None:
                arr_new = np.zeros((arr.shape[0], n_correct))
                for s in range(arr.shape[0]):
                    arr_new[s, :] = np.interp(
                        CENTRALITY_CENTERS_CORRECT, stored_centers, arr[s, :]
                    )
                remapped[key] = arr_new
        remapped['centrality_centers'] = CENTRALITY_CENTERS_CORRECT.copy()
        return remapped


def clip_predictions_to_exp_range(pred_data, exp_data):
    """
    Return a view of pred_data restricted to centrality bins that fall within
    the experimental centrality range [exp_min, exp_max].
    Clips prior, original_posterior, and posterior arrays.
    """
    cent = np.asarray(pred_data['centrality_centers'])
    exp_max = exp_data['centrality'].max()
    exp_min = exp_data['centrality'].min()

    mask = (cent >= exp_min) & (cent <= exp_max)
    clipped = pred_data.copy()
    clipped['centrality_centers'] = cent[mask]
    for key in ('prior', 'original_posterior', 'posterior'):
        if clipped.get(key) is not None:
            clipped[key] = clipped[key][:, mask]
    return clipped


# =============================================================================
# LOAD EXPERIMENTAL DATA
# =============================================================================

def load_experimental_v0_global(filepath):
    """Load experimental global v0 vs centrality from CSV file"""
    if not Path(filepath).exists():
        print(f"Warning: Experimental data file '{filepath}' not found!")
        return None

    # Load CSV
    data = pd.read_csv(filepath, comment='#')

    # Find first section (pT^ref = 0.5-2 GeV)
    first_section_end = None
    for i, row in data.iterrows():
        if i > 0 and str(row.iloc[0]) == 'Centrality [%]':
            first_section_end = i
            break

    if first_section_end is not None:
        data = data.iloc[:first_section_end].copy()

    # Convert to numeric
    for col in data.columns:
        data[col] = pd.to_numeric(data[col], errors='coerce')

    # Rename columns
    data.columns = ['centrality', 'v0', 'stat_plus', 'stat_minus', 'sys_plus', 'sys_minus']

    # Calculate errors
    stat_err = np.abs(data['stat_plus'].values)
    sys_err  = np.abs(data['sys_plus'].values)
    total_err = np.sqrt(stat_err**2 + sys_err**2)

    print(f"  ✓ Loaded ATLAS 5.02 TeV data: {len(data)} centrality bins")
    print(f"  Centrality values: {data['centrality'].values}")

    return {
        'centrality': data['centrality'].values,
        'v0':         data['v0'].values,
        'stat_err':   stat_err,
        'sys_err':    sys_err,
        'total_err':  total_err
    }


# =============================================================================
# LOAD & PREPROCESS PREDICTION DATA
# =============================================================================

def load_predictions(filepath):
    """Load prediction data from pickle file"""
    if not Path(filepath).exists():
        print(f"ERROR: Prediction file '{filepath}' not found!")
        print("Please run predict_global_v0.py first to generate predictions.")
        return None

    with open(filepath, 'rb') as f:
        predictions = pickle.load(f)

    return predictions


def preprocess_predictions(all_predictions, exp_data):
    """
    Apply centrality remapping and clipping to all prediction entries.
    Returns a new dict with corrected centrality_centers.
    """
    processed = {}
    for corr, pred_data in all_predictions.items():
        print(f"\n  Processing {corr}:")
        # Step 1: remap centrality centers to correct ATLAS bin centers
        remapped = remap_predictions_to_correct_centrality(pred_data)
        # Step 2: clip to experimental range
        if exp_data is not None:
            clipped = clip_predictions_to_exp_range(remapped, exp_data)
            n_clipped = len(clipped['centrality_centers'])
            print(f"    Clipped to {n_clipped} bins within exp range "
                  f"[{exp_data['centrality'].min():.1f}%, "
                  f"{exp_data['centrality'].max():.1f}%]")
            processed[corr] = clipped
        else:
            processed[corr] = remapped
    return processed


# =============================================================================
# PLOTTING FUNCTIONS
# =============================================================================

def _ratio_band(ax, cent_centers, pred_arr, exp_data, color, alpha, lw, label=None):
    """Helper: interpolate a prediction array onto exp centrality, compute ratio, plot."""
    env = np.percentile(pred_arr, [5, 50, 95], axis=0)
    env_interp = np.zeros((3, len(exp_data['centrality'])))
    for i in range(3):
        env_interp[i, :] = np.interp(exp_data['centrality'], cent_centers, env[i, :])
    ratio_low = env_interp[0, :] / exp_data['v0']
    ratio_med = env_interp[1, :] / exp_data['v0']
    ratio_high = env_interp[2, :] / exp_data['v0']
    ax.fill_between(exp_data['centrality'], ratio_low, ratio_high, color=color, alpha=alpha)
    ax.plot(exp_data['centrality'], ratio_med, color=color, lw=lw, alpha=0.9, label=label)


def plot_global_v0_single_correction(corr, pred_data, exp_data):
    """
    Plot global v0 for a single correction with model/data ratio panel.
    Layers (bottom→top):
      1. Prior 90% C.I.          — gray hatched
      2. Original posterior 90%  — orange  (Grad only)
      3. Correction posterior 90%— correction color
      4. Experimental data       — black markers
    """
    fig, axes = plt.subplots(2, 1, figsize=(10, 10),
                             gridspec_kw={'height_ratios': [3, 1]},
                             sharex=True)
    ax_top = axes[0]
    ax_bot = axes[1]
    fontsize = 20

    cent_centers = pred_data['centrality_centers']

    # X-axis limits
    x_min = exp_data['centrality'].min() - 3 if exp_data is not None else 0
    x_max = exp_data['centrality'].max() + 3 if exp_data is not None else 95

    # ------------------------------------------------------------------
    # Layer 1 — Prior 90% C.I.
    # ------------------------------------------------------------------
    if pred_data.get('prior') is not None:
        pr_env = np.percentile(pred_data['prior'], [5, 50, 95], axis=0)
        ax_top.fill_between(cent_centers, pr_env[0, :], pr_env[2, :],
                            hatch='///', edgecolor='gray', facecolor='gray',
                            alpha=0.35, lw=1.5, label='Prior 90% C.I.')
        ax_top.plot(cent_centers, pr_env[1, :], color='gray',
                    lw=1.5, ls='--', alpha=0.8)
        if exp_data is not None:
            _ratio_band(ax_bot, cent_centers, pred_data['prior'],
                        exp_data, color='gray', alpha=0.25, lw=1.5)

    # ------------------------------------------------------------------
    # Layer 2 — Original JETSCAPE posterior (Grad only, orange)
    # ------------------------------------------------------------------
    if pred_data.get('original_posterior') is not None:
        orig_env = np.percentile(pred_data['original_posterior'], [5, 50, 95], axis=0)
        ax_top.fill_between(cent_centers, orig_env[0, :], orig_env[2, :],
                            color='orange', alpha=0.45,
                            label='Original JETSCAPE Posterior 90% C.I.')
        ax_top.plot(cent_centers, orig_env[1, :], color='orange',
                    lw=2.5, alpha=0.9)
        if exp_data is not None:
            _ratio_band(ax_bot, cent_centers, pred_data['original_posterior'],
                        exp_data, color='orange', alpha=0.35, lw=2.5)

    # ------------------------------------------------------------------
    # Layer 3 — Correction-specific posterior
    # ------------------------------------------------------------------
    if pred_data.get('posterior') is not None:
        post_env = np.percentile(pred_data['posterior'], [5, 50, 95], axis=0)
        ax_top.fill_between(cent_centers, post_env[0, :], post_env[2, :],
                            color=COLOR_NAMES[corr], alpha=0.4,
                            label=f'{corr} Posterior 90% C.I.')
        ax_top.plot(cent_centers, post_env[1, :], color=COLOR_NAMES[corr],
                    lw=2.5, alpha=0.9)
        if exp_data is not None:
            _ratio_band(ax_bot, cent_centers, pred_data['posterior'],
                        exp_data, color=COLOR_NAMES[corr], alpha=0.35, lw=2.5)
    else:
        print(f"  ✗ No posterior predictions for {corr}")

    # ------------------------------------------------------------------
    # Layer 4 — Experimental data
    # ------------------------------------------------------------------
    if exp_data is not None:
        ax_top.errorbar(exp_data['centrality'], exp_data['v0'],
                        yerr=exp_data['total_err'],
                        fmt='o', color='black', markersize=7, capsize=4,
                        linewidth=2, alpha=0.95, label='ATLAS 5.02 TeV', zorder=10)

        # Ratio panel: exp uncertainty on unity line
        exp_rel_err = exp_data['total_err'] / exp_data['v0']
        ax_bot.errorbar(exp_data['centrality'], np.ones_like(exp_data['centrality']),
                        yerr=exp_rel_err, fmt='o', color='black',
                        markersize=7, capsize=4, linewidth=2, alpha=0.95, zorder=10)

    # Formatting — top panel
    ax_top.set_ylabel(r"$v_0$", fontsize=fontsize + 8)
    ax_top.legend(loc='best', frameon=False, fontsize=fontsize - 4)
    ax_top.set_ylim(0, 0.10)
    ax_top.axhline(0, color='black', linestyle='--', linewidth=0.8, alpha=0.5)
    ax_top.set_xlim(x_min, x_max)
    configure_axis(ax_top, fontsize - 2)

    # Formatting — bottom panel
    ax_bot.axhline(1.0, color='k', lw=1.5, ls='--')
    ax_bot.set_xlabel("Centrality [%]", fontsize=fontsize + 8)
    ax_bot.set_ylabel("Model/Data", fontsize=fontsize - 2)
    ax_bot.grid(True, alpha=0.3)
    ax_bot.set_ylim(0.5, 1.5)
    ax_bot.set_xlim(x_min, x_max)
    configure_axis(ax_bot, fontsize - 2)

    plt.tight_layout(rect=[0, 0, 1, 0.98])
    plt.subplots_adjust(hspace=0.05)

    return fig


def plot_global_v0_all_corrections(all_predictions, exp_data):
    """
    Plot global v0 for all corrections overlaid with model/data ratio panel.
    Predictions and experimental data share aligned centrality bins.
    """
    fig, axes = plt.subplots(2, 1, figsize=(12, 10),
                             gridspec_kw={'height_ratios': [3, 1]},
                             sharex=True)

    ax_top = axes[0]
    ax_bot = axes[1]

    fontsize = 20

    # X-axis limits: span the experimental centrality range only
    x_min = exp_data['centrality'].min() - 3 if exp_data is not None else 0
    x_max = exp_data['centrality'].max() + 3 if exp_data is not None else 95

    # ------------------------------------------------------------------
    # Layer 1 — Prior (use first available; all corrections share same prior)
    # ------------------------------------------------------------------
    prior_plotted = False
    for corr in VISCOUS_CORRECTIONS:
        if corr not in all_predictions or prior_plotted:
            continue
        pred_data = all_predictions[corr]
        if pred_data.get('prior') is None:
            continue
        cent_centers = pred_data['centrality_centers']
        pr_env = np.percentile(pred_data['prior'], [5, 50, 95], axis=0)
        ax_top.fill_between(cent_centers, pr_env[0, :], pr_env[2, :],
                            hatch='///', edgecolor='gray', facecolor='gray',
                            alpha=0.35, lw=1.5, label='Prior 90% C.I.')
        ax_top.plot(cent_centers, pr_env[1, :], color='gray', lw=1.5, ls='--', alpha=0.8)
        if exp_data is not None:
            _ratio_band(ax_bot, cent_centers, pred_data['prior'],
                        exp_data, color='gray', alpha=0.25, lw=1.5)
        prior_plotted = True

    # ------------------------------------------------------------------
    # Layer 2 — Original JETSCAPE posterior (Grad only, orange)
    # ------------------------------------------------------------------
    for corr in VISCOUS_CORRECTIONS:
        if corr not in all_predictions:
            continue
        pred_data = all_predictions[corr]
        if pred_data.get('original_posterior') is None:
            continue
        cent_centers = pred_data['centrality_centers']
        orig_env = np.percentile(pred_data['original_posterior'], [5, 50, 95], axis=0)
        ax_top.fill_between(cent_centers, orig_env[0, :], orig_env[2, :],
                            color='orange', alpha=0.45,
                            label='Original JETSCAPE Posterior 90% C.I.')
        ax_top.plot(cent_centers, orig_env[1, :], color='orange', lw=2.5, alpha=0.9)
        if exp_data is not None:
            _ratio_band(ax_bot, cent_centers, pred_data['original_posterior'],
                        exp_data, color='orange', alpha=0.35, lw=2.5)

    # ------------------------------------------------------------------
    # Layer 3 — Correction-specific posteriors
    # ------------------------------------------------------------------
    for corr in VISCOUS_CORRECTIONS:
        if corr not in all_predictions:
            continue
        pred_data = all_predictions[corr]
        if pred_data.get('posterior') is None:
            continue
        cent_centers = pred_data['centrality_centers']
        post_env = np.percentile(pred_data['posterior'], [5, 50, 95], axis=0)
        ax_top.fill_between(cent_centers, post_env[0, :], post_env[2, :],
                            color=COLOR_NAMES[corr], alpha=0.3)
        ax_top.plot(cent_centers, post_env[1, :], color=COLOR_NAMES[corr],
                    lw=2.5, alpha=0.9, label=f'{corr} Posterior')
        if exp_data is not None:
            _ratio_band(ax_bot, cent_centers, pred_data['posterior'],
                        exp_data, color=COLOR_NAMES[corr], alpha=0.25, lw=2.5)

    # ------------------------------------------------------------------
    # Layer 4 — Experimental data
    # ------------------------------------------------------------------
    if exp_data is not None:
        ax_top.errorbar(exp_data['centrality'], exp_data['v0'],
                        yerr=exp_data['total_err'],
                        fmt='o', color='black', markersize=7, capsize=4,
                        linewidth=2, alpha=0.95, label='ATLAS 5.02 TeV', zorder=10)
        # Experimental uncertainty band on ratio panel
        exp_rel_err = exp_data['total_err'] / exp_data['v0']
        ax_bot.errorbar(exp_data['centrality'], np.ones_like(exp_data['centrality']),
                        yerr=exp_rel_err, fmt='o', color='black',
                        markersize=7, capsize=4, linewidth=2, alpha=0.95, zorder=10)

    # Formatting — top panel
    ax_top.set_ylabel(r"$v_0$", fontsize=fontsize + 8)
    ax_top.legend(loc='best', frameon=False, fontsize=fontsize - 4, ncol=2)
    ax_top.set_ylim(0, 0.10)
    ax_top.axhline(0, color='black', linestyle='--', linewidth=0.8, alpha=0.5)
    ax_top.set_xlim(x_min, x_max)
    configure_axis(ax_top, fontsize - 2)

    # Formatting — bottom panel
    ax_bot.axhline(1.0, color='k', lw=1.5, ls='--')
    ax_bot.set_xlabel("Centrality [%]", fontsize=fontsize + 8)
    ax_bot.set_ylabel("Model/Data", fontsize=fontsize - 2)
    ax_bot.grid(True, alpha=0.3)
    ax_bot.set_ylim(0.5, 1.5)
    ax_bot.set_xlim(x_min, x_max)
    configure_axis(ax_bot, fontsize - 2)

    plt.tight_layout(rect=[0, 0, 1, 0.98])
    plt.subplots_adjust(hspace=0.05)

    return fig


def print_comparison_summary(all_predictions, exp_data):
    """Print summary of model vs data comparison"""
    print("\n" + "=" * 80)
    print("MODEL VS DATA COMPARISON SUMMARY")
    print("=" * 80)

    if exp_data is not None:
        print(f"\nExperimental Data (ATLAS 5.02 TeV):")
        print(f"  Centrality bins: {len(exp_data['centrality'])}")
        print(f"  Centrality centers: {exp_data['centrality']}")
        print(f"  v0 range: {exp_data['v0'].min():.5f} - {exp_data['v0'].max():.5f}")

    print(f"\nModel Predictions (centrality centers after remapping):")
    for corr in VISCOUS_CORRECTIONS:
        if corr not in all_predictions:
            continue
        pred_data = all_predictions[corr]
        if pred_data['posterior'] is None:
            continue

        cent_centers = pred_data['centrality_centers']
        post_pred    = pred_data['posterior']
        post_median  = np.median(post_pred, axis=0)

        print(f"\n  {corr}:")
        print(f"    Centrality centers: {cent_centers}")
        print(f"    Median v0 range: {post_median.min():.5f} - {post_median.max():.5f}")

        if exp_data is not None:
            post_med_interp = np.interp(exp_data['centrality'], cent_centers, post_median)
            ratios = post_med_interp / exp_data['v0']
            print(f"    Model/Data ratio range: {ratios.min():.3f} - {ratios.max():.3f}")
            print(f"    Mean Model/Data ratio:  {ratios.mean():.3f} ± {ratios.std():.3f}")

    print("\n" + "=" * 80)


# =============================================================================
# MAIN EXECUTION
# =============================================================================

if __name__ == "__main__":
    print("\n" + "=" * 80)
    print("PLOTTING GLOBAL v0 PREDICTIONS VS ATLAS 5.02 TeV DATA")
    print("=" * 80)

    # Load experimental data
    print("\nLoading experimental data...")
    exp_data = load_experimental_v0_global(EXP_V0_FILE)

    # Load raw prediction data
    print("\nLoading prediction data...")
    all_predictions_raw = load_predictions(PREDICTIONS_FILE)

    if all_predictions_raw is None:
        print("\nERROR: Could not load predictions.")
        print("Please run predict_global_v0.py first.")
        exit(1)

    print(f"✓ Loaded predictions for: {list(all_predictions_raw.keys())}")

    # -------------------------------------------------------------------------
    # KEY FIX: remap centrality centers and clip to experimental range
    # -------------------------------------------------------------------------
    print("\nRemapping and clipping prediction centrality bins...")
    all_predictions = preprocess_predictions(all_predictions_raw, exp_data)

    # Print comparison summary
    print_comparison_summary(all_predictions, exp_data)

    # Create plots
    print("\n" + "=" * 80)
    print("CREATING PLOTS...")
    print("=" * 80)

    # Plot 1: Combined plot with all corrections
    print("\n1. Creating combined plot with all corrections...")
    if exp_data is not None:
        fig_combined = plot_global_v0_all_corrections(all_predictions, exp_data)
        save_fig(fig_combined, 'global_v0_all_corrections_vs_exp.pdf')

    # Plot 2-5: Individual plots for each correction
    print("\n2. Creating individual plots for each correction...")
    for corr in VISCOUS_CORRECTIONS:
        if corr not in all_predictions:
            continue
        print(f"   Plotting {corr}...")
        fig = plot_global_v0_single_correction(corr, all_predictions[corr], exp_data)
        if fig is not None:
            save_fig(fig, f'global_v0_{corr}_vs_exp.pdf')

    print("\n" + "=" * 80)
    print("✓ PLOTTING COMPLETE")
    print(f"Output folder: {OUTPUT_FOLDER}/")
    print("=" * 80 + "\n")
